# Generated by Django 6.0b1 on 2025-11-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_student2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
