# Generated by Django 6.0b1 on 2025-11-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_student_created_at_remove_student_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student2',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='student2',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
