# Generated by Django 6.0b1 on 2025-11-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_transactions_options_remove_transactions_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
